name: functions-build

# Run when creating a PR or commits
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      # Checks-out repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: What is in the cache?
        run: npm config get cache
      # Attempt to restore from cache

      # Install dependencies
      - name: Fetching Dependencies...
        run: npm ci
      # Clean Cache
      - name: Clean cache
        run: npm cache clean --force
